# Generated by Django 5.1.1 on 2024-09-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_book_pdf_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdfes',
            field=models.ManyToManyField(blank=True, related_name='books', to='myapp.pdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
