# Generated by Django 5.1.1 on 2024-09-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_pdf_uploaded_at_book_cover_image_book_pdfes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='book',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('equipo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('ano', models.DateField()),
                ('posicion', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('pdfes', models.ManyToManyField(blank=True, related_name='players', to='myapp.pdf')),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='myapp.player'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
