# Generated by Django 5.1.1 on 2024-09-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_pdf_player'),
    ]

    operations = [
    ]
